### ISSUE TITLE
Size doesn't work ?

### ISSUE THREAD

**Issue by Birssan** [getgrav/grav-plugin-shortcode-core#1]
Hello there,

I've tried to use the size shortcode like this `[size=10]test[/size]`

Here is the result:

```
<span style="font-size: =10px;">test</span>
```

Am I the only one ?

**Comment by rhukster** [comment]
This might be the result of me switching to the wordpress parser.  I'll test it, might have to go back to the regex parser.

**Comment by Birssan** [comment]
Thanks for fixing it so fast :)
