### ISSUE TITLE
Unexpected error message when updating v5.0.4 to v.5.0.5

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-shortcode-core#103]
When trying to update the most recent v.5.0.5 Shortcode Core release, the following error message appears and I cannot seem to actually update the plugin:

![](https://user-images.githubusercontent.com/1812771/110982510-70853380-831d-11eb-9946-e94387e0f6ca.png)

Please let me know if more info is helpful etc.

Thanks very much,  
Paul

**Comment by rhukster** [comment]
Just ran into this myself and trying to work out what's going on!

**Comment by rhukster** [comment]
shortcode-core is the only one you are having issues with right?

**Comment by paulhibbitts** [comment]
Yes, but I've got everything else up-to-date in my installs so only plugin needing an update.

**Comment by paulhibbitts** [comment]
I've been able to update a site online... perhaps this is a GitHub connection issue/local setup. I will close this issue for now and reopen if I can't resolve the issue. Thanks!

**Comment by rhukster** [comment]
I re-released, i think there was some hiccup on Github's side during the last release as everything looked fine on GPM side.

**Comment by paulhibbitts** [comment]
Thanks @rhukster , I've just tried again and can now update Shortcode Core locally👍 Cheers!
