### ISSUE TITLE
Shortcodes fail to render

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-plugin-shortcode-core#106]
Hello,

I'm a new user, using the Admin Panel with Shortcode Core, activated globally with these settings:

enabled: true
active: true
active_admin: true
admin_pages_only: true
parser: regular
include_default_shortcodes: true
css:
  notice_enabled: true
custom_shortcodes: null
fontawesome:
  load: true
  url: //maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
  v5: false
nextgen-editor:
  env: production
  dev_host: localhost
  dev_port: 2001

Nonetheless, no shortcodes seem to render. No shortcodes have been disabled. Shortcodes instead get parsed with `<p></p>` tags.

Even if I manually edit the .md file for a page to remove the `<p></p>` tags, shortcodes still don't get recognized.

Thanks in advance for any assistance getting this set up.

**Comment by key-notes** [comment]
Update: This may be an issue with a specific shortcode. It appears that default shortcodes do render, but the shortcode defined in the [FullCalender](https://github.com/wernerjoss/grav-plugin-fullcalendar) plugin does not. Can anyone help?

**Comment by rhukster** [comment]
You should create an issue on fullcalendar repo as it’s an issue with that plugin’s shortcode and not the core plugin. Cheers.
