### ISSUE TITLE
Call to undefined method Grav\Common\Page\Page::getContentMeta()

### ISSUE THREAD

**Issue by rdquintas** [getgrav/grav-plugin-shortcode-core#12]
Hi there,
I've been trying to install and use this plugin, but no matter what I do, I always get this error

Am I doing anything wrong ?

![2016-03-06 18_14_55](https://cloud.githubusercontent.com/assets/3330729/13556001/7f34cdf0-e3c7-11e5-8cc8-41b91a587adf.jpg)

Many Thanks

**Comment by rdquintas** [comment]
Ran command
`php bin/gpm self-upgrade`

and problem solved :smile:

**Comment by rhukster** [comment]
Yup, needed a newer Grav version.  Glad you got it sorted.
