### ISSUE TITLE
Looks like safe-email does not work.

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-shortcode-core#128]
Looks like safe-email does not work.
Latest version (1.7.46) of GRAV, skeleton: Learn2 with Git Sync Site v1.6.7

I've read https://discord.com/channels/501836936584101899/521762967851630621/619356698146111489 (Run onContentProcessed() event after all other plugins) about the issue, but I am somehow unable to fix this.

**Comment by rhukster** [comment]
Are you 'sure' it's not working? have you viewed the source? the elements inspector will convert special chars automatically. Only by viewing source can you see the 'raw' output.

**Comment by awrog** [comment]
Thanks for reaching out!
plugin: Shortcode Core  v5.2.0
demo here: https://lrp-netwerk.pkn.nl/xtranet/faq
shortcode:  `[safe-email autolink="true" icon="envelope-o" subject="inloggen Extranet"]info@protestantsekerk.nl[/safe-email]`
part of frontmatter:
```YAML
process:
    markdown: true
    twig: true
twig_first: true
```
generated html:
`<p><i class="fa fa-envelope-o"></i> <a href="mailto:info@protestantsekerk.nl?subject=inloggen%20Extranet">info@protestantsekerk.nl</a></p>`

**Comment by rhukster** [comment]
Ah try remove that process and twig_first bit.. i think that is interfering by converting the escaped characters back to non-escaped.

**Comment by awrog** [comment]
Removed the process: and twig_first from the frontmatter.
Even placed it in a [different page](https://lrp-netwerk.pkn.nl/xtranet/vragen-en-opmerkingen) with no other shortcodes present.

It still generates `<p><i class="fa fa-envelope-o"></i> <a href="mailto:info@protestantsekerk.nl?subject=inloggen%20Extranet">info@protestantsekerk.nl</a></p>`

theme: Learn2 Git Sync v1.6.4
GRAV: Grav v1.7.46

**Comment by awrog** [comment]
After updating to Grav grav-update-v1.7.47, the shortcode works again as expected.
