### ISSUE TITLE
Exception error just after installing plugin

### ISSUE THREAD

**Issue by ArnauBlanch** [getgrav/grav-plugin-shortcode-core#13]
Hi,
I've installed the plugin several times but I always receive an error message that breaks my whole site after installing the plugin. I attach you a screenshot of it:
![captura de pantalla 2016-03-22 a les 17 52 56](https://cloud.githubusercontent.com/assets/5014931/13960115/3deb4710-f057-11e5-8003-7f4dde7c319a.png)

I hope you can help me with this issue.
Thanks!

**Comment by rhukster** [comment]
Update Grav to latest version.

**Comment by ArnauBlanch** [comment]
Oh, thank you. :grin:
