### ISSUE TITLE
Shortcode Section not showing in Listpage

### ISSUE THREAD

**Issue by wsanter** [getgrav/grav-plugin-shortcode-core#15]
Hi,
i tried Shortcode Section with a fresch grav-skeleton-blog-site installation and it's displayed correctly on the blog.page, but not on the homepage.

Thank you!

Userfolder is attached
[user.zip](https://github.com/getgrav/grav-plugin-shortcode-core/files/228390/user.zip)

**Comment by rhukster** [comment]
Works fine on my homepage, but to get data 'from' the homepage you should use the `/home` route or whatever the page is routed under.
