### ISSUE TITLE
Font Awesome Shortcodes Not Loaded

### ISSUE THREAD

**Issue by cd13sr** [getgrav/grav-plugin-shortcode-core#16]
When installing this via the Admin panel or though the terminal, the Font Awesome shortcodes are no where to be found.

Thanks.

**Comment by flaviocopes** [comment]
Hi, what you mean "no where to be found"? You're looking for a button or something to enter them, or you're saying they (https://github.com/getgrav/grav-plugin-shortcode-core#fontawesome) don't work?

**Comment by cd13sr** [comment]
Sorry for the confusion. The Font Awesome shortcodes don't work ([fa=cog /]) because the /shortcodes/FontAwesomeShortcode.php file doesn't exist when installing this plugin from the Admin panel or from a terminal.

Thanks.

**Comment by rhukster** [comment]
Do you have version 2.2.0 installed? That is when font awesome was added.

Try doing a `bin/gpm update`

**Comment by rhukster** [comment]
Oh i see the problem.  2.2.0 was never fully released.  it was tagged but not released actually. So my fault! I'll fix now.

**Comment by cd13sr** [comment]
No problem, just thought you should know!
