### ISSUE TITLE
Forms in modular pages doesn't work enabling shortcode-core plugin

### ISSUE THREAD

**Issue by salgua** [getgrav/grav-plugin-shortcode-core#17]
Hi,
I created a modular form following [this instructions](https://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages). It works fine, but if I enable the shortcode-core plugin the form stops to work.

**Comment by flaviocopes** [comment]
Could be the same issue with modular forms and the Assets plugin? Will look into adding a shortcode to add a form, to change how forms can be added to modular pages as currently it's a bit clunky and prone to such problems.

**Comment by rhukster** [comment]
i think this should be addressed with post Forms 2.0. Please reopen if it's not the case.
