### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-plugin-shortcode-core#2]
Hi,
this is not an issue but a proposal, as the title suggests. :-) 

I deeply deal with shortcodes these days and I made my Gravstrap plugin completely working using shortcodes, instead of using Yaml configuration to configure components.

I've abstracted the shortcode declaration and I'd like to ask you if you might consider to evaluate that work to be added to this plugin. Here's the directory where I implemented the base classes I'd like to add to shortcode-core plugin https://github.com/giansi/gravstrap/tree/shortcodes/classes/Base and here you will find an implementation example: https://github.com/giansi/gravstrap/tree/shortcodes/classes/Accordion.

Here it is how the plugin initializes the shortcodes: https://github.com/giansi/gravstrap/blob/shortcodes/gravstrap.php.

If you think this could be helpful for this plugin, I will port this piece of library to yours.

**Comment by rhukster** [comment]
I'm definitely up for improving the core shortcode plugin to make extending it even more powerful.

Without me having to dig in to deep, can you tell me what all the different Base classes are used for?  I see you have an interface and some abstract classes, but you are inheriting the base in most cases? What about if you just had one base class with the key bits in it?

I'm all for simplifying if possible :)

Also, maybe you can fork the core plugin and submit a PR with your request.  it's kinda hard to have to work out what's specific to your custom stuff and what would be considered appropriate for the core.

**Comment by giansi** [comment]
Great. I will work on it!

**Comment by rhukster** [comment]
Any progress on this PR? Going to do a release today, so will have to wait until the next one.

**Comment by giansi** [comment]
Sorry no, it is not ready yet. We'll wait until the next one
