### ISSUE TITLE
Latest Update breaks section shortcode!

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-core#20]
I just installed shortcode-core 2.3.1. Now the section shortcode isnt't rendered anymore.  Reinstalled old section-shortcode.php and composer.json, everything is fine again???

**Comment by rhukster** [comment]
Did you clear the cache? Sections are working fine in my testing setup.

**Comment by rhukster** [comment]
btw if you are manually retrieving shortcodes then that has changed a bit:

```
<div id="author">{{ page.find('/my/custom/page').contentMeta.shortcodeMeta.shortcode.section.author }}</div>
```

Had to namespace the shortcodes due to clashes.  Updated the README.md and mentioned in the changelog.

**Comment by axel-rank** [comment]
Tried again clearing all caches, same thing, after reinstall of old shortcode-core.php everything works again.

**Comment by rhukster** [comment]
How are you using the shortcodes? because i can't replicate any problem.

**Comment by rhukster** [comment]
Oh I know what it probably is, this requires Grav 1.1 which we're in the process of releasing now.
