### ISSUE TITLE
Last update destroys GravStrap menus

### ISSUE THREAD

**Issue by 2braincells2go** [getgrav/grav-plugin-shortcode-core#21]
Was working on new site using Gravstrap. Got notice of update for shortcode core and did so. Now the header / footers menus are gone, totally missing from entire site. Downgraded to version b4 update and all menus restored.

I am also working on a new bootstrap theme for Grav and it was effected same way.

Thanks!

Woody

**Comment by rhukster** [comment]
Have you also left a message on the gravstrap plugin issue tracker? The changes made to core should be transparent to the user as they happen in the core plugin alone, so any other 'shortcode' plugin should be 100% compatible.  However, there have been some other issues with Gravstrap plugin specifically in the past with core updates, so probably that plugin is doing more than the standard shortcode logic.  

https://github.com/giansi/gravstrap/issues

**Comment by 2braincells2go** [comment]
Issue fixed by Gravstrap Plugin update.

I am slowly learning the Grav platform. This little bump actually was a good thing, better understand the flow:)

Thanks much.
