### ISSUE TITLE
Custom shortcodes in theme

### ISSUE THREAD

**Issue by metadiv** [getgrav/grav-plugin-shortcode-core#23]
Is it possible to add new custom shortcodes in a location outside of the plugins folder? Like a new folder in the `user/` folder or as part of a theme?

**Comment by flaviocopes** [comment]
A theme is just a plugin (https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Theme.php#L14) so you can add anything that belongs to a plugin inside a theme, too.

**Comment by rhukster** [comment]
Yup, i've already done this in the past, just use a plugin like `shortcode-owl-carousel` as an example.

**Comment by GittiHab** [comment]
Hi, I am trying to add a shortcode to a theme but it doesn't seem to work – this is driving me crazy. This is my full theme code:

```
<?php
namespace Grav\Theme;
use Grav\Common\Theme;

class MyTheme extends Theme
{

    /**
     * Register events
     */
    public static function getSubscribedEvents()
    {
//        echo 'TEST'; exit; // this works, so the theme should be intialized.

        return [
            'onShortcodeHandlers' => ['onShortcodeHandlers', 0]
        ];
    }
    /**
     * Event that handles registering handler for shortcodes
     */
    public function onShortcodeHandlers()
    {
        // is never called?!
        $this->grav['shortcode']->registerShortcode('MyShortcode.php', __DIR__);
    }

}
```

Any ideas why this is?
