### ISSUE TITLE
Override parser

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav-plugin-shortcode-core#24]
Is there a way for my shortcode plugin to override the shortcode-core `parser` setting? I tried just adding a `parser` setting to my config file, but that didn't do it. I'm having trouble with my new shortcode recognizing quoted parameters containing spaces.

**Comment by Perlkonig** [comment]
So my quoting problem was because of the smartypants plugin. I'm still curious about overriding the parser setting, though. Thanks!

**Comment by rhukster** [comment]
You can actually just set the value via the config object:

```
$this-grav['config']->set('plugins.shortcode-core.parser', 'regex');
```

Just make sure you set this early enough that the config is there, but before any parsing is done. Should do it.
