### ISSUE TITLE
update meant lost of colors

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav-plugin-shortcode-core#27]
With the update, the color tag do not work anymore. I understood that there is a need to create a new plugin from now on! May be a little bit to difficult for me though...
How show I do?

**Comment by rhukster** [comment]
Color tag is working for me.  Make sure you have the parser set to `regex`.  Some changes happened in this past release and we changed the default parser to `regex` where it was `wordpress` before.  I had to fix some issues that this caused.
