### ISSUE TITLE
no columns in firefox

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-core#28]
installed latest shortcode-core 2.5.1. though you added moz-columns --> no columns in firefox.
cleared all caches, tried diffrent processor settings...no columns

**Comment by rhukster** [comment]
Did you clear the cache? And what version of Firefox. Needs to be 50 at least I think.

**Comment by axel-rank** [comment]
Firefox 50.1.0
Cleared all caches.

**Comment by rhukster** [comment]
Try upgrading Firefox.

**Comment by axel-rank** [comment]
Same on Firefox 51.

**Comment by rhukster** [comment]
Ok, i had bad CSS.. should be fixed in next release.

**Comment by axel-rank** [comment]
yes, working now.
