### ISSUE TITLE
Latest Update Breaks FontAwesome

### ISSUE THREAD

**Issue by WeAreELIC** [getgrav/grav-plugin-shortcode-core#30]
Hey, I just updated to the latest version and my FontAwesome icons break. It looks like it not honoring the following Markdown formats:

[fa=cog /] Simplest Format
[fa=fa-cog /] Format using fa- prefix

It is however, honoring this format: [fa icon=fa-cog /].

I haven't tested the "extras" options yet.

Thanks.

**Comment by rhukster** [comment]
We made a change in this release to make the library more compatible with the "Regex" processor, which is the preferred processor.  Please change it from "Wordpress" and you should be working again.

**Comment by WeAreELIC** [comment]
Beautiful, thanks for the quick reply!
