### ISSUE TITLE
Current shortcode processing hook comes too late

### ISSUE THREAD

**Issue by sunyatasattva** [getgrav/grav-plugin-shortcode-core#32]
Seems like the current hook is too late for several use-cases.

## Example 1: Shortcodes and assets on modular pages

As seen in [this issue](
https://github.com/getgrav/grav-plugin-shortcode-ui/issues/14), shortcodes don't correctly add assets when used in modular pages.

## Example 2: Markdown processing

As seen in [this PR](https://github.com/getgrav/grav-plugin-shortcode-core/pull/22), shortcodes might add unwanted markup.

**Comment by rhukster** [comment]
Changing the processing breaks many shortcodes that have/need markdown being processed withing the shortcodes.  If you wish to remove the markdown-produced html, you can strip those tags out.

**Comment by sunyatasattva** [comment]
Do you mind me asking for an example of such use case and why couldn't those shortcodes implement their own Markdown parsing when needed? In this way shortcodes which don't need it, don't have a choice.

And what do you mean by strip those tags out?
