### ISSUE TITLE
Custom Shortcodes removed with update

### ISSUE THREAD

**Issue by metadiv** [getgrav/grav-plugin-shortcode-core#36]
I am running a site that uses the shortcodes plugin and I have created a few custom shortcodes in the `/user/plugins/shortcode-core/shortcodes/` folder. 

But every time I update the plugin they are removed. I have backups which I can replace the missing files with but is there a way to create a folder outside of the plugin directory (either in a `user/theme/myCustomTheme/` or directly in the `user/` folder) that can be read by the plugin but not updated (thus removing any custom contents)?

**Comment by rhukster** [comment]
You cannot put custom code in an existing plugin.  Any update will simply overwrite your edits/additions.

You could simply duplicate an existing simple shortcode plugin like Owl Carousel (https://github.com/getgrav/grav-plugin-shortcode-owl-carousel) and use that to house your custom plugins.

I can create a very simple plugin that does similar but can load shortcodes from a user-provided directory.

**Comment by metadiv** [comment]
Thanks for the reply. For the moment I can continue to manually re insert my shortcodes. But this is a company site that I might not always be in charge of and it would be nice to future proof it. if the shortcode-core could just look for a folder called `/user/shotcodes/` that would be amazingly simple and robust in the spirit of Grav's file inheritance?

**Comment by rhukster** [comment]
Ok, added for next release.
