### ISSUE TITLE
Disabling shortcode parser markdown

### ISSUE THREAD

**Issue by koyal13** [getgrav/grav-plugin-shortcode-core#38]
Hi @rhukster I'm developing a chart-shortcode and I have to disable markdown parser in my plugin. I discovered some public methods in ShortcodeManager class like `setupMarkdown` or `processContent`, I need it becouse I'm trying to "parse" json and/or yml data. Do you think is it suitable?

**Comment by koyal13** [comment]
Right now I solved it removing html tags on php... But is there any better way to avoid markdown processing?

**Comment by rhukster** [comment]
You can disable markdown processing at the page level with:

```
process:
  markdown: false
```

You can also set it programitically on the page with:

```
$page->process(['markdown' => false']);
```

of course this would need to be set prior to the `$page->content()` method being called as that's where markdown is processed if enabled.

The better option is to do some work in `onPageContentRaw()` event which is called prior to `processMarkdown()` function in the `content()` method.

**Comment by koyal13** [comment]
So, I think it would be interesting to see an option or function to retrieve shortcode content without formatting. Anyway I'm going to make some attemps with `onPageContentRaw()` and `onShortcodeHandlers` Wish me luck! ;)

**Comment by hamiltont** [comment]
Years late, but I had the same issue and figured I would share what worked OK for me: 

```
    public static function getSubscribedEvents()
    {
        require_once(__DIR__.'/vendor/autoload.php');        
        return [ 'onShortcodeHandlers' => ['onShortcodeHandlers', 0] ,
                 'onPageContentRaw' => ['getRaw', 0]];
    }
    public function getRaw(Event $e) {
        $page = $e['page'];
        $content = $page->content();
        // <snip> 
        // Some simple "find my shortcode" string processing
        // logic, since "$content" is just a big unparsed string at this point
        // </snip>
       $page->addContentMeta('customSCMeta', $scContents);
    }
```

Later on in my extension I just check if that meta key is set. If it is set, I completely ignore the result of `shortcode->getContents()` and instead use the raw contents pulled from the meta

HTH
