### ISSUE TITLE
Where to put custom shortcode files

### ISSUE THREAD

**Issue by milojennings** [getgrav/grav-plugin-shortcode-core#41]
I can't quite seem to figure out where to put a custom shortcode in order to get it working correctly. I tried creating a PHP file in the `/user/custom/shortcodes` folder, and as a standalone plugin. Either way I get the error: 
```Class 'Grav\Plugin\Shortcodes\Shortcode' not found```

Could you perhaps provide the exact steps of where to put the files to create a simple shortcode? 

Thank you.

**Comment by rhukster** [comment]
you need to create your own plugin.  They are very simple to create (especially with devtools plugin), and there are several examples. https://github.com/getgrav/grav-plugin-shortcode-core/blob/develop/README.md#developing-shortcode-plugins

**Comment by milojennings** [comment]
Thanks for getting back to me, I appreciate your time.
I have tried creating a plugin. I even used the devtools plugin. When active, I see the following error:

```Fatal error: Class 'Grav\Plugin\Shortcodes\Shortcode' not found in /home/59504-47928.cloudwaysapps.com/knqwskaxsz/public_html/user/plugins/km-shortcodes/km-shortcodes.php on line 11```

Perhaps you could point me in the right direction. I must be doing something obviously wrong, I just can't see it. Here's the code for my plugin at the moment:

```
<?php
namespace Grav\Plugin\Shortcodes;
use Thunder\Shortcode\Shortcode\ShortcodeInterface;

class KMChildPages extends Shortcode
{
    public function init()
    {
        $this->shortcode->getHandlers()->add('child_pages', function(ShortcodeInterface $sc) {
            $depth = $sc->getParameter('depth', $sc->getBbCode());
            return '<span>Display '.$depth.' levels deep</span>';
        });
    }
}
```

**Comment by rhukster** [comment]
Take a look at this one as an example https://github.com/getgrav/grav-plugin-shortcode-media

**Comment by milojennings** [comment]
Thank you @rhukster, that helped. After quite a bit of frustrating trial and error I discovered that the filename of the shortcode has to match the the name of the class.

So if you name your class `ChildpagesShortcode`, your file must be named `ChildPagesShortcode.php` and placed in the `shortcodes/` folder.

That was the key. Now it works, and I can happily build shortcodes. Thanks!
