### ISSUE TITLE
Rendering Twig Template with Shortcode

### ISSUE THREAD

**Issue by GittiHab** [getgrav/grav-plugin-shortcode-core#42]
Hi, I have a simple question here:
If I have a shortcode I want to render a Twig Template. How would I go about implementing this in Grav?

Example: My shortcode is `[news]` when this occurs the template `partials/news.twig` (i.e. `{% include 'partials/news.twig' %}`) should be inserted into the page. Is this possible or is this too late when the shortcodes are rendered?

**Comment by rhukster** [comment]
It should be doable, just output the string.  If you have `process: twig: true` on the page it should process that.

**Comment by GittiHab** [comment]
Thanks, I will try that...
