### ISSUE TITLE
Theme not receiving onShortcodeHandlers event

### ISSUE THREAD

**Issue by GittiHab** [getgrav/grav-plugin-shortcode-core#43]
Hi, I am trying to add a shortcode to a theme but it doesn't seem to work – this is driving me crazy. This is my full theme code:

```
<?php
namespace Grav\Theme;
use Grav\Common\Theme;

class MyTheme extends Theme
{

    /**
     * Register events
     */
    public static function getSubscribedEvents()
    {
//        echo 'TEST'; exit; // this works, so the theme should be intialized.

        return [
            'onShortcodeHandlers' => ['onShortcodeHandlers', 0]
        ];
    }
    /**
     * Event that handles registering handler for shortcodes
     */
    public function onShortcodeHandlers()
    {
        // is never called?!
        $this->grav['shortcode']->registerShortcode('MyShortcode.php', __DIR__);
    }

}
```

Any ideas why this is?

**Comment by GittiHab** [comment]
As I understood #23 this should be possible. As I am looking at the code though the `onShortcodeHandlers` event seems to be fired before the themes are initialized (because my theme also doesn't receive `onPluginsInitialized`). Therefore the fix was to subscribe to the `onThemesInitialized` event and register the shortcodes there – this does not seem to be a good behavior.

It would be cool if the event is either fired when the themes are also initialized or changing the core Grav event system.

**Comment by finanalyst** [comment]
I think this is a ***bug*** or design feature!

I have written several plugins defining shortcodes and I like the flexibility. So I tried to add one to a new theme (overiding Antimatter).

Problem is: `Shortcode-Core` plugin fires the `'onShortcodeHandlers'` event from inside `'onPluginsInitialized'`, but this comes **before** `'onThemesInitialized'`. Consequently, the Shortcode php I define in my themes is not activated, and I cannot hook into `onPluginsInitialized` from a theme.

a) I _think_ Shortcode-Core needs to move the line where the `onShorecodeHandlers` event is fired in shortcode-core.php from line #53, which is in the `onPluginsInitialized` function into a Grav hook after the `onThemesInitialized` event hook (may be `OnTask` ?).
b) If this is not possible for some reason, the a way to register a shortcode at a later date needs to be included in the Documentation.
c) It seems from the Grav Lifecycle that there is no hook before `onPluginsInitialized` that I could put my theme shortcode initiation in. 

It is possible - but this is a Grav design question - that there **should** be a clear distinction between plugin and theme code. But if that is the case, then this should be spelled out in both the Theme and Plugin dox. Currently, the Theme indicates anything that Plugins can do, so can Themes.

**Comment by mgollmer** [comment]
I agree. I would also like to be able to define shortcodes within the theme. Makes totaly sense to me.

**Comment by mgollmer** [comment]
Just imagin... What would happen if we fire the event a second time? During the theme-initialization for example?

**Comment by rhukster** [comment]
Should be fixed in develop... Sorry for the delay

**Comment by mgollmer** [comment]
Thank you, Sir.

**Comment by finanalyst** [comment]
When will the fix land?

**Comment by mgollmer** [comment]
Already there.
