### ISSUE TITLE
Shortcode replace p tags by div

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav-plugin-shortcode-core#44]
After having used `[center][/center]` around some text in a markdown, I found out that the result was some raw text on the web page, _stripped_ from all the CSS.

The reason is the CSS I built is defined on `<p>` tags, and that the Shortcode plugin outputs text lines in `<div>`, with just inline `"style"` attribute. Here is the sourcecode : 

`<p><div style="text-align: center;">Envoyez un message à l'aide du formulaire de contact ou contactez-nous par téléphone.</div></p>`

But styling `<div>` to render text properly is more difficult than styling `<p>` tags, and can lead to conflicts. Not mentioning that they are not made for this semantic purpose. **So, my suggestion would be to fix the problem by _embedding correctly_ the content catched by the plugin !** For instance : 
    `<div style="text-align: center;">`
        `<p>Some text<p>`
    `</div>`

Or, more efficiently, by acting on the `<p>` tag itself : 
    `<p style="text-align: center;">Some text</p>`

**Comment by rhukster** [comment]
You can't really change the current implementation, but you could copy it to your own plugin / theme, and change it to `ctr` something and output the `<p>` instead of `<div>`
