### ISSUE TITLE
Updating fontawesome?

### ISSUE THREAD

**Issue by Simbaclaws** [getgrav/grav-plugin-shortcode-core#46]
Is it possible to override the version of font-awesome used by the shortcode core plugin?
Hopefully, so people can override the font-awesome version themselves in case they need to.
Something like a setting in a yaml file would be nice.

If this is not possible, could you please update font-awesome to version 5?
I would like to use an icon that doesn't yet exist in 4.

**Comment by speedbomb** [comment]
I'm not very familiar with pull requests, so i'll attach some code that allows to use the new v5 font family classes _fab_, _fal_, _fas_ and _far_:
```
            if($icon) {
                $fa_class = 'fa';
                $extras = explode(',', $sc->getParameter('extras', ''));

                foreach($extras as $extra) {
                    if(!empty($extra)) {
                        if(in_array($extra, array('fab', 'fal', 'fas', 'far'))) {
                            $fa_class = $extra;
                            continue;
                        }
                        if(!Utils::startsWith($extra, 'fa-')) {
                            $extra = 'fa-' . $extra;
                        }
                        $icon .= ' ' . $extra;
                    }
                }

                $output = '<i class="' . $fa_class . ' ' . $icon . '">' . $str . '</i>';

                return $output;
            }
```
Replace this into File [shortcodes/FontAwesomeShortcode.php](https://github.com/getgrav/grav-plugin-shortcode-core/blob/develop/shortcodes/FontAwesomeShortcode.php) at line 25.

For testing purposes i have added the CDN version of Font Awesome:
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
```
This allows e.g. a spinning Grav icon with the Shortcode `[fa icon=fa-grav extras=fab,fa-spin /]`

**Comment by rhukster** [comment]
I would maybe make your own, because i've found FA5 to not be 100% compatible with FA4

**Comment by rhukster** [comment]
merged

**Comment by speedbomb** [comment]
Great! Thank You! :D

**Comment by rhukster** [comment]
I just realized that with the latest 4.0 version of shortcode-core, it probably won't work on Grav 1.5, but it will with 1.6-RC.4.  As it depends on the new 'deferred' block functionality for adding assets to work.

I am going to add the deferred extension to 1.5, but it does require a minor fix in the theme to take advantage of it.

```
{% block assets deferred %}
    {{ assets.css()|raw }}
    {{ assets.js()|raw }}
{% endblock %}
```

**Comment by onetrev** [comment]
So if you enable FA5, you then have to manually update the "Fontawesome URL" setting to something like so: `//use.fontawesome.com/releases/v5.8.0/css/all.css`?

Just thinking this may cause confusion for some users if that's the case. But not sure if there is an easy fix?

**Comment by rhukster** [comment]
it's a bit complicated, the logic i had before to get the assets and add them before the twig rendered, was actually breaking a number of plugins, and also modular forms.

I have a better way to do it using the deferred block capability, and ive added this to Grav 1.5 and i will release this very soon, but will require a change in the theme as outlined above.
