### ISSUE TITLE
Shortcode breaks modular Forms

### ISSUE THREAD

**Issue by gmpreussner** [getgrav/grav-plugin-shortcode-core#47]
I'm using the Forms v2.13.3 and Shortcode Core v2.7.1 plug-ins in Grav v1.4.3. As soon as I enable the Shortcode Core plug-in, forms inside modular pages no longer get populated (only the container HTML is generated, but no dynamic content, such as input fields and buttons).

I'm using the classical method of rendering forms in modular pages as described in the Grav manual, i.e. my parent page contains the form frontmatter, and the modular page consists of form.md with the following contents:

```
---
title: 'My Form'
cache_enable: false
---
```

**Comment by rhukster** [comment]
i've seen this reported before but i'm stil unable to replicate it.  Are there other plugins in the mix?

**Comment by gmpreussner** [comment]
Here's a list of the plug-ins I have installed and enabled:

* DevTools  v1.1.1
* Error  v1.6.1
* Feed  v1.6.2
* Form  v2.14.1
* Highlight  v1.4.0
* Log Errors v1.0.1
* Markdown Notices  v1.0.1
* Pagination  v1.3.2
* Problems  v1.4.7
* Sitemap  v1.9.1
* YouTube  v2.0.4

**Comment by rhukster** [comment]
My test site has all of those except "log errors" and "youtube"... mind disabling those, clearing cache and testing?

**Comment by gmpreussner** [comment]
Ok, I'm currently on the road. I'll give it a shot tomorrow.

**Comment by m4rkinh0** [comment]
Hello !
I have the same problem. Here is the plugins I am using.

![shortcode](https://user-images.githubusercontent.com/38053524/40629308-8c1ea49e-62ca-11e8-9754-0995759010c4.jpg)

**Comment by m4rkinh0** [comment]
Hi !
How can I help with this open point ?

**Comment by rhukster** [comment]
How about creating a ZIP of the `user/` folder where you are having this problem?

**Comment by m4rkinh0** [comment]
Thank you very much.
I used solution number 2 and it works like a charm.
