### ISSUE TITLE
Can't nest shortcodes?

### ISSUE THREAD

**Issue by benninkcorien** [getgrav/grav-plugin-shortcode-core#50]
I can't seem to nest div's/shortcodes with this plugin?

```
[div class="row"]
[div class="x12 s12 m12 l12"]
## Header
[/div]
[/div]
```

Gives the following output HTML

```
<div class="row">
<div class="x12 s12 m12 l12">
</div>
<h2>Header:</h2>
</div>
[/div]
```

Expected result:

```
<div class="row">
<div class="x12 s12 m12 l12">
<h2>Header</h2>
</div>
</div>
```

**Comment by rhukster** [comment]
It's actually a problem with the shortcode parser.  If you switch the parser (in `shortcode-core.yaml` configuration) to `regular` parser, then it works.

The reason the default parser is on `regex` is for performance reasons, but the `regular` parser has improved, and I'll probably make it the default parser in the next release.

**Comment by rhukster** [comment]
BTW 2.7.2 released with `regular` parser as default + latest Shortcode library updates
