### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by crusnac** [getgrav/grav-plugin-shortcode-core#53]
After upgrading the lasted version, I am getting a memory error:

`E_ERROR - Allowed memory size of 134217728 bytes exhausted (tried to allocate 1052672 bytes)`

Using GRAV v1.5.4

**Comment by crusnac** [comment]
It looks like changing parser: regular -> parser: regex in shortcode-core.yaml fixes this problem.

**Comment by rhukster** [comment]
This is a problem with the `regular` parser on certain content.  You are correct `regex` parser doesn't seem to have these problems.  I've submitted an issue against the upstream repo:

https://github.com/thunderer/Shortcode/issues/71

**Comment by thunderer** [comment]
@crusnac I implemented necessary changes in thunderer/Shortcode#72, once @rhukster verifies it on his side I will release new stable library version and you will be able to use RegularParser again. Long story short: I found over 100x performance gain so neither time nor memory will be a problem now. Thanks for using Shortcode and Grav (and sorry for the issues)! :smile:

**Comment by rhukster** [comment]
Thanks to @thunderer for fixing this in version 0.7.0.  I've released a shortcode-core plugin update with version `3.0.0` that includes the latest library release plus a new setting to give more control in the admin.  By default shortcodes will only be processed in page content, increasing performance for regular admin rendering.
