### ISSUE TITLE
Error on page using shortcode

### ISSUE THREAD

**Issue by Nithilher** [getgrav/grav-plugin-shortcode-core#57]
Just updated the shortcode-core plugin. After that, I get the following error on the one page where I make use of shortcode:

Argument 1 passed to Grav\Plugin\ShortcodeManager::getId() must implement interface Thunder\Shortcode\Shortcode\ShortcodeInterface, null given, called in /Users/phytzel/Sites/grav/user/plugins/shortcode-ui/shortcodes/AccordionsShortcode.php on line 33

The error page lists the following chunk from 
/Users/phytzel/Sites/grav/user/plugins/shortcode-core/classes/ShortcodeManager.php

```

    /**
     * returns the shortcode of a specific hash
     * 
     * @param  string $hash       unique id of state
     * @return ShortcodeInterface shortcode stored for this hash
     */
    public function getStates($hash)
    {
        if (array_key_exists($hash, $this->states)) {
            return $this->states[$hash];
        }
    }
 
    /**
     * helper method to create a unique shortcode based on the content
     * 
     * @param  ShortcodeInterface $shortcode
     * @return string             
     */
    public function getId(ShortcodeInterface $shortcode)
    {
        return substr(md5($shortcode->getShortcodeText()), -10);
    }
 
    /**
     * Sets the current page context
     *
     * @param Page $page
     */
    public function setPage(Page $page)
    {
```

and highlights the line with getId().

It appears that the new shortcode-core does not work properly together with shortcode-ui. 

Which further output should I provide?

**Comment by rhukster** [comment]
Shortcode-ui problem.  Will look there...

**Comment by rhukster** [comment]
Related to this issue https://github.com/getgrav/grav-plugin-shortcode-ui/issues/29
