### ISSUE TITLE
Assets are not added to page

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-plugin-shortcode-core#6]
Here's my shortcode:

    class JumbotronShortcode extends Shortcode
    {
    public function init()
    {
        $this->shortcode->getHandlers()->add('gravstrap-jumbotron', function(ShortcodeInterface $shortcode) {
            
            $this->shortcode->addAssets('css', 'plugin://gravstrap/css/gravstrap_jumbotron.css');
            
            $output = $this->twig->processTemplate('bootstrap/jumbotron.html.twig', [
                'id' => $shortcode->getParameter('id'),
                'image' => $shortcode->getParameter('image'),
                'fullwidth' => $shortcode->getParameter('fullwidth'),
                'content' => $shortcode->getContent(),
            ]);
            
            return $output;
        });
    }
    }

The 'plugin://gravstrap/css/gravstrap_jumbotron.css' asset is not added to page.

**Comment by rhukster** [comment]
Are you running the latest version of Grav? Latest release is needed for this to work correctly as I had to add a new `contentMeta` caching mechanism.

**Comment by giansi** [comment]
Related to #5.
