### ISSUE TITLE
Size SC with named & other units

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav-plugin-shortcode-core#62]
CSS allows for the `font-size` attribute to have values such as `x-large`, and units such as `pt` or `%`. 

Current implementation of `[size=...]` sticks `px` onto the parameter. This reduces flexibility.

Suggest change so that `px` is concatenated to parameter value only when parameter is a number.

See PR #63

**Comment by rhukster** [comment]
Merged.. thanks.
