### ISSUE TITLE
Color Breaks in Grav 1.5.8 / Shortcode Core 3.1.0

### ISSUE THREAD

**Issue by RyanMPierson** [getgrav/grav-plugin-shortcode-core#64]
WordPress parser (default setting) is broken in the latest Grav + Shortcode Core. Switching to Regex or Regular fixes it. Color renders as a span without the color assignment on WordPress parser.

**Comment by rhukster** [comment]
Might be best to raise the issue on the upstream thunderer/shortcode project.

**Comment by rhukster** [comment]
I can't replicate this with latest shortcode-core.  Wordpress parser renders text fine, although I recommend using 'regular' parser as the others don't support nested shortcodes.
