### ISSUE TITLE
Nested [div]s not working in twig |markdown filter

### ISSUE THREAD

**Issue by rblinde** [getgrav/grav-plugin-shortcode-core#67]
When using the `|markdown` filter on a markdown field created in a page blueprint, nested `[div]` do not work properly. Example:

```markdown
[div class="columns"]
[div]
## title
paragraph
[/div]
[div]
paragraph
[/div]
[/div]
```
Should render html as:
```html
<div class="columns">
  <div>
    <h2>title</h2>
    <p>paragraph</p>
  </div>
  <div>
    <p>paragraph</p>
  </div>
</div>
```
But instead I get:
```html
<div class="columns">
  <div></div>
  <h2>subtitle</h2>
  <p>paragraph</p>
</div>
<div>
  <p>paragraph</p>
</div>
[/div]
```

In the template, I use: `{{- page.header.introduction|markdown|shortcodes -}}`.

I have tried:
- Processing Twig/Markdown
- Switching parsers in the plugin
- Purging all Cache

I have found a temporary workaround using `[section]`_markdown_`[/section]` in the default content editor. So nested `[div]` do work in the default editor. But I would like to have a seperate Introduction editor.

**Comment by rhukster** [comment]
Make sure you have your `parser:`  set to `regular`. That's the only parser that supports nested tags.
