### ISSUE TITLE
The readme talk about a custom_shortcodes directory, but there is no documentation about how to use it

### ISSUE THREAD

**Issue by lilive** [getgrav/grav-plugin-shortcode-core#68]
Hi,

Really nice plugin, thank you.

The readme mention:

> custom_shortcodes: the path to a directory where you can put your custom shortcodes (e.g. /user/custom/shortcodes)

But there is no clue about how to create custom shortcodes this way. Is it possible ? I ended up to create my custom shortcodes by creating a plugin, as adviced later on the readme, and it works like a charm, but I'm still confused about this custom_shortcodes option.

**Comment by rhukster** [comment]
You can take a look at some of the other plugins that provide custom shortcodes:

https://github.com/getgrav?utf8=%E2%9C%93&q=shortcode&type=&language=

**Comment by lilive** [comment]
Thank you for this quick answer, but I don't see which of these plugins offer the ability for an user to define its own shortcode.
Just to be sure, because my english is not so good : have you understood that I was able to easily create some new shortcodes by creating a new plugin ? The readme contains good directions to achieve this. My question is not about a custom shortcode plugin, but about another way to create a shortcode with this mysterious custom_shortcodes directory.

**Comment by rhukster** [comment]
Sorry, didn't fully get the question originally.

It's been a while so had to look at the code to remember:

```php
    /**
     * Event that handles registering handler for shortcodes
     */
    public function onShortcodeHandlers()
    {
        $this->shortcodes->registerAllShortcodes(__DIR__.'/shortcodes');

        // Add custom shortcodes directory if provided
        $custom_shortcodes = $this->config->get('plugins.shortcode-core.custom_shortcodes');
        if (isset($custom_shortcodes)) {
            $this->shortcodes->registerAllShortcodes(GRAV_ROOT . $custom_shortcodes);
        }
    }
```

Basically you can set a directory, e.g. `/user/shortcodes/` and then put custom shortcodes in here and they will get picked up.  You still need to write the PHP shortcodes like the ones in the plugin's `shortcode/` directory: https://github.com/getgrav/grav-plugin-shortcode-core/tree/develop/shortcodes

**Comment by lilive** [comment]
I see, thank you. And I realize now that I could have understood this my myself, the code you show me is simple enough, sorry.
I've just created some custom shorcodes this way, it works. This seems convenient to me, simplier than create another plugin.
I can propose to improve de readme on this topic, and to send a PR. What do you think ?

**Comment by rhukster** [comment]
I added some info to the README

**Comment by lilive** [comment]
Nice !
Thank you.
