### ISSUE TITLE
Section isn't showing after update

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-shortcode-core#69]
Hello! After updating Grav from 1.3 to 1.6 and all plugins too my shortcodes section are not showing. No errors on page or console, just white space where must be a text.
Cache is cleared, tried to change Parser without success.

Ideas?

I use them like this in *.md:
```markdown
[section name="objective"]
Text-text
[/section]
```
and in twig:
```yaml
<div class="alt-features-descr align-left">
    {{ shortcode.section.objective }}
</div>
```

**Comment by rhukster** [comment]
Please try with `regular` parser.

**Comment by Sogl** [comment]
Tried before with all parser combinations, nothing works. 
Just tried again with `regular` and the same problem.

**Comment by rhukster** [comment]
Hmm.. it still works for me in latest Grav.  I have this in a file called `shortcode.md`:

```
[section name="author"]
![](affinity.jpg?cropResize=100,100&classes=left)
### Johnny Appleseed
Johnny Appleseed was an American pioneer nurseryman who introduced apple trees to large parts of Pennsylvania, Ontario, Ohio, Indiana, and Illinois, as well as the northern counties of present-day West Virginia. He became an American legend while still alive, due to his kind, generous ways, his leadership in conservation, and the symbolic importance he attributed to apples.
[/section]
```

Then in a `shortcode.html.twig` template I have:

```twig
<div style="border:1px solid red">{{ shortcode.section.author }}</div>
```

Output:

<img width="1001" alt="Image 2019-06-28 at 1 57 46 PM" src="https://user-images.githubusercontent.com/1084697/60367915-bb75e080-99ac-11e9-84ea-7a9b327bf3a8.png">


Working with cache on or off.

**Comment by Sogl** [comment]
My site is multilanguage, in both languages the same problem.
What I need to check in my PHP/Grav/etc configuration?

**Comment by rhukster** [comment]
I don't think multilanguage should make a difference as long as the shortcode is defined in each of the language pages.  I'll try to test this more this weekend.

**Comment by Sogl** [comment]
`{{ dump(shortcode) }}` and `{{ dump(shortcode.section) }}`shows `null` in debugbar.

**Comment by rhukster** [comment]
What version of
Grav and shorcofe-core are you on?

**Comment by Sogl** [comment]
I had Grav 1.3.3 with this list of plugins and `section` worked:
![image](https://user-images.githubusercontent.com/7556290/60389997-5964ca80-9ad5-11e9-8a3a-d30a429cba06.png)

Now I have Grav 1.6.11 and nevest plugins:
![image](https://user-images.githubusercontent.com/7556290/60390014-b496bd00-9ad5-11e9-8c75-b27d6dbd3967.png)

**Comment by Sogl** [comment]
I found a workaround from an old issue: https://github.com/getgrav/grav-plugin-shortcode-core/issues/5#issuecomment-183718431

If i use `{{ grav.shortcode.objects.section.objective }}` instead of `{{ shortcode.section.objective }}` it works and I can see my text on the page.

**Comment by Sogl** [comment]
@rhukster Any news on this?

**Comment by rhukster** [comment]
I don’t know how to replicate the issue.  Works fine in all my testing setups.  What else (plugins) do you have installed that could be effecting this?

**Comment by Sogl** [comment]
My plugin list is here: https://github.com/getgrav/grav-plugin-shortcode-core/issues/69#issuecomment-506991372

**Comment by rhukster** [comment]
Fixed this in latest release..

**Comment by Sogl** [comment]
@rhukster So what was the problem?

**Comment by rhukster** [comment]
Content was not processed so sections were not available.  I had twig processing on the page enabled so it was working for me. When I disabled that I saw the issue.
