### ISSUE TITLE
Share sections between pages

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-plugin-shortcode-core#7]
Sections open new scenarios and it would be awesome to get the chance to share them between site pages.

**Comment by rhukster** [comment]
I foresaw this and already added the ability to do this:  See the last bit of the README.md:

https://github.com/getgrav/grav-plugin-shortcode-core/blob/develop/README.md#sections-from-other-pages:

> ### Sections from other pages
>
> You can even retrieve a section from another page utilizing the shortcodes as they are stored in the  page's contentMeta with this syntax:
>
> ```
> <div id="author">{{ page.find('/my/custom/page').contentMeta.shortcode.section.author }}</div>
> ```
