### ISSUE TITLE
Release 4.1.3 seems to be causing Page URL issues, resulting in 404's

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-shortcode-core#73]
The newest release (4.1.3) seems to be causing Page URL issues, where a page path passed to a Shortcode is not being rendered as expected.

For example, here is a page using the Presentation Shortcode, which was working up to the release of 4.1.3:
http://test.hibbittsdesign.org/grav-skeleton-open-matter-presentation-hub-site/page-with-presentation

Shortcode syntax:
`[presentation="/presentations/placeholder-slides"]`

Chatting with Ole about this issue, he flagged this code that might be related:
https://github.com/getgrav/grav-plugin-shortcode-core/blob/4.1.3/shortcode-core.php#L233

Might it be possible to revert to 4.1.2 for now, as this issue is causing all of my skeletons which use Presentation shortcodes to not work? Happy to help test possible fixes etc.

Thanks very much,
Paul

**Comment by rhukster** [comment]
mabye its the bbcode style shortcode syntax?  Is there an alternate longer syntax?

**Comment by OleVik** [comment]
Yes, using `src`, but it falls back to bbCode: https://github.com/OleVik/grav-plugin-presentation/blob/master/shortcodes/PresentationShortcode.php#L44.

**Comment by rhukster** [comment]
Does removing the `$page->content()` fix the issue?

**Comment by paulhibbitts** [comment]
Hi @rhukster @OleVik , yes I just did a quick local test and removing that line the shortcode rendered the URL correct.

**Comment by rhukster** [comment]
Ok, i'll have to find an alternative solution because this was a fix for something else.

**Comment by paulhibbitts** [comment]
Thanks so much for looking into it @rhukster!

**Comment by paulhibbitts** [comment]
Hi @rhukster , as a short-term fix for my four skeletons I thought I would make ShortCode Core 1.4.2 a dependency during theme install - however, this format does not seem to work:

`- { name: shortcode-core, version: '=4.1.2' }`

Am I doing something wrong here?
Thanks!

**Comment by rhukster** [comment]
it only works with `>` or `>=` i think.  This is because GPM only knows about the latest version, it doesn't keep track for all versions.

**Comment by rhukster** [comment]
BTW can you please test with the latest fix?

**Comment by paulhibbitts** [comment]
Great news @rhukster , that fix works for several test sites of mine! Thank you so much for looking into this issue🙂

**Comment by rhukster** [comment]
Cool, released as v4.1.4 .. should show up in next hour
