### ISSUE TITLE
Safe-email shortcode no longer working?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-shortcode-core#75]
In the past I've used the Safe-email shortcode and I thought when I first checked the resulting html via "view-source" the email address info was obfuscated. I've just started to use the shortcode again (after I recommended it to another educator for their course site) but I seem to have the email address in plain text:

```
<i class="fa fa-envelope"></i> <a href="mailto:paul_hibbitts@sfu.ca" class="mailto">paul_hibbitts@sfu.ca</a>
```

Here is the shortcode syntax I am using:
`[safe-email autolink="true" icon="envelope"]paul_hibbitts@sfu.ca[/safe-email]`

Am I doing something wrong or is this an issue with the Plugin?

Thanks very much,
Paul
ps - here is a live site with an example, please see the sidebar https://paulhibbitts.net/cmpt-363/193/home

**Comment by rhukster** [comment]
The Inspector will show it as plain text, but "view source" should show it obfuscated. 

It doesn't appear to be obfuscated on your site though.

It is working on my test site with the shortcode:

```
<h3>Safe Email</h3>

 <p>Safe-Email Address: <i class="fa fa-envelope-o"></i> <a href="mailto:&#117;&#115;&#101;&#114;&#64;&#100;&#111;&#109;&#97;&#105;&#110;&#46;&#99;&#111;&#109;">&#117;&#115;&#101;&#114;&#64;&#100;&#111;&#109;&#97;&#105;&#110;&#46;&#99;&#111;&#109;</a></p>
```

**Comment by paulhibbitts** [comment]
Thanks so much for confirming it does work on your end @rhukster. I just tested with my Open Publishing Space and it is not obfuscating there either. I will try to dig deeper to see if it is something those two skeletons share (BTW, both themes have their own custom shortcodes, but I do not see that a factor).

**Comment by paulhibbitts** [comment]
Hi @rhukster , I think I've tracked down the issue at least in one case. With my Bootstrap4 Open Matter the External Links Plugin is a dependency and when this Plugin is Enabled the safe-mail shortcode does not seem to work. Once it is disabled it works, and also if you set the External Links Plugin `Order of execution` to `1`. So, now this site works👍https://paulhibbitts.net/cmpt-363/193/home

However, for some reason in my Quark Open Publishing theme the above alone does not get the safe-mail shortcode work - I also need to disable the Image Captions plugin... any ideas?

Thanks very much,
Paul

**Comment by rhukster** [comment]
I will install imageCaptions in parallel and test.

**Comment by rhukster** [comment]
OK, i can confirm that with image-captions a similar issue occurs.. It's basically because those plugins are doing manipulation in the same event as shortcode-core, and shortcode-core is running first, and obfuscating the email correctly, but when the other plugins do their thing, that encoded HTML is automatically decoded back to normal.

You were on the right track, but rather than making the external links plugin run earlier, i'm going to ensure the shortcode-core plugin runs later (ie, -10 order), this way it should always run last after other plugins that use the same event.

**Comment by paulhibbitts** [comment]
Thanks very much @rhukster, it's great you were able to replicate the issue! Your solution sounds perfect👍Thank you.

**Comment by rhukster** [comment]
and released

**Comment by paulhibbitts** [comment]
Works perfectly, thanks again Andy!

**Comment by OleVik** [comment]
Just to note, this change will have broken rendering in events hooking into `onPageContentProcessed` and using Shortcode Core for third-party shortcodes. To remedy this, event priorities should be changed to be lower or equal to - per [Admin#999](https://github.com/getgrav/grav-plugin-admin/issues/999) - the new [`-10`](https://github.com/getgrav/grav-plugin-shortcode-core/blob/4.1.5/shortcode-core.php#L49).
