### ISSUE TITLE
Section Shortcode not working since 4.14 release

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-core#77]
Sections shortcode does not show up anymore. This issue came up with 4.14 release.
Think it's related to this commit:
https://github.com/getgrav/grav-plugin-shortcode-core/issues/73
Cause if I change shortcode-core.php from 4.14 to 4.13 release sections show up again.

**Comment by rhukster** [comment]
Sections working fine for me.  What does your `shortcode-core.yaml` config look like?

**Comment by rhukster** [comment]
BTW this is my test page twig:

```twig
{% extends 'partials/base.html.twig' %}


{% block content %}

  {{ page.content|raw }}

  <h2>Shortcodes in Twig file `{% verbatim %}{{ twig_text|shortcodes }}{% endverbatim %}`</h2>

  {% set twig_text = "This is [size=30]bigger text[/size] and this is [color=green]green text[/color]" %}
  {{ twig_text|shortcodes|raw }}

  <h2>Section Includes</h2>

  <div style="border:1px solid red">
    {{ shortcode.section.author|raw }}
  </div>

  <div style="border:1px solid blue">{{ shortcode.section.quote|raw }}</div>

  <h2>From another page</h2>

  {% verbatim %}
    <pre><div id="author">{{ page.find('/plugins/shortcode/core').contentMeta.shortcodeMeta.shortcode.section.dummy_section|raw }}</div></pre>
  {% endverbatim %}

  <div id="author">{{ page.find('/plugins/shortcode/core').contentMeta.shortcodeMeta.shortcode.section.dummy_section|raw }}</div>

{% endblock %}
```

**Comment by axel-rank** [comment]
user/config/plugins/shortcode-core.yaml

![Bildschirmfoto_2019-09-30_19-27-53](https://user-images.githubusercontent.com/12480617/65901469-94b6b400-e3b8-11e9-80cd-3651f17a496f.png)

Tried different parser, cleared all caches...really didn't change anything...was working fine until 4.14

**Comment by rhukster** [comment]
What other plugins do you have installed? It's probably the change in event ordering.

https://github.com/getgrav/grav-plugin-shortcode-core/commit/e7e8e3b6c66c5e716b27fe3951db2779ceb16af6

**Comment by axel-rank** [comment]
![Bildschirmfoto_2019-09-30_19-39-31](https://user-images.githubusercontent.com/12480617/65902191-1b1fc580-e3ba-11e9-94b8-6fb3bc2b1fc0.png)

**Comment by rhukster** [comment]
Same issue with 4.1.5 version?

**Comment by axel-rank** [comment]
Yes

**Comment by rhukster** [comment]
So if you change:

```
 'onPageContentProcessed'    => ['onPageContentProcessed', 0],
```

 in onPluginsInitalized does it start working?

**Comment by axel-rank** [comment]
No

**Comment by rhukster** [comment]
See all the changes here.. not much really changed that would effect "Sections":

https://github.com/getgrav/grav-plugin-shortcode-core/compare/4.1.4...develop

What version of Grav are you running?

**Comment by axel-rank** [comment]
It's the same issue in GRAV 1.6.16 and 1.7.0-beta.9

**Comment by rhukster** [comment]
I had the wrong 'compare'.. looking through it now..: https://github.com/getgrav/grav-plugin-shortcode-core/compare/4.1.3...4.1.4

**Comment by rhukster** [comment]
Oh are you doing your twig in page content? or is it in a dedicated .twig file?

**Comment by rhukster** [comment]
Better zip up your user folder so i can try to work out why it's not working for you

**Comment by axel-rank** [comment]
No, no twig in page content. Dedicated .twig file? I have a modular page with different sections...using agency theme.

**Comment by rhukster** [comment]
Ok, modular page.  that could be it.  if you disable cache on that modular page does it start working?

**Comment by rhukster** [comment]
BTW, things were changed in 4.1.3 regarding how twig was processed because it didn't work at all in certain scenarios.  The new approach was intended to fix those issues.

**Comment by axel-rank** [comment]
I don't use cache. Set to disabled in my system.yaml

**Comment by rhukster** [comment]
ok, its definitely related to modular pages.. i'm looking..

**Comment by rhukster** [comment]
Please try the latest version from develop. I've changed how the twig vars are handled so I could add some logic so that it will work in Modular and Regular pages.

BTW, the reason it had trouble was the Twig is processed so much earlier in Modular pages, so the content_meta had no chance to process and store as a twig variable before it was called.

**Comment by axel-rank** [comment]
Yes, working again! Great! Thank You.

**Comment by rhukster** [comment]
I'll release tomorrow.. cheers!
