### ISSUE TITLE
Shortcode variable is null in a modular page

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-plugin-shortcode-core#8]
Looks like in a modular page, shortcode variable is always null, independently by cache setting. Here's a working example: https://www.dropbox.com/s/r145zli0gi1l44u/gravstrap.tar.gz?dl=0

Page to check is /gravstrap-theme-simple-page-example (sorry the nav menu is not rendered). I put a {{ dump(shortcode) }} in the twig template, home_single_page.html.twig, and I got null, The cache is disabled.

**Comment by rhukster** [comment]
Ok tracked down the problem.  Basically shortcode-core was only setting the twig vars in `onTwigSiteVariables()` event.  This is not available when Modular pages are rending, so i needed to add some logic for `onTwigPageVariables()`.  So should be good after next release.

**Comment by rhukster** [comment]
ok fixed in latest release.

**Comment by giansi** [comment]
Just tried and it does not work for me. When I have this setting in my page's header:

    content:
      items: @self.modular
      order:
        by: default
        dir: asc
        custom:
            - _what_we_do
            - _portfolio
            - _clients
            - _team
            - _where_we_are
            - _contacts

shortcode variable is still null

**Comment by rhukster** [comment]
I think your confused as to the way modular pages work. It's quite similar to a blog list in that the `modular.html.twig` template loops over a page collection to create the resulting total page.  Each modular page though gets it's `content()` method called and in each of those modular sub pages.  The shortcodes are then associated with each modular sub-page, not the parent page.

The way I tested was to use the one-page skeleton and then add an 'author' section shortcode to the 'showcase.md` modular page.  Then I added a `{{ shortcode.section.author }}` in the `templates/modular/showcase.html.twig` file that renders it, and it worked fine.

BTW, you should be able to get to the shortcodes from each modular page with the `page.find()` technique.

**Comment by giansi** [comment]
Got it.
