### ISSUE TITLE
ErrorException 4.2.1 version

### ISSUE THREAD

**Issue by HarDX** [getgrav/grav-plugin-shortcode-core#82]
Whoops \ Exception \ ErrorException (E_ERROR)
Class Grav\Plugin\Shortcodes\Shortcodes\Assets contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Grav\Plugin\Shortcodes\Shortcode::init)

3
Whoops\Exception\ErrorException 
…/user/plugins/shortcodes/classes/Shortcodes/Assets.php0
2
Whoops\Run handleError
…/vendor/filp/whoops/src/Whoops/Run.php408
1
Whoops\Run handleShutdown
…/system/src/Grav/Common/Errors/SystemFacade.php37
0
Grav\Common\Errors\SystemFacade handleShutdown
[internal]0

**Comment by HarDX** [comment]
4.1.7 is works fine, after update to last, errorexception...

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav-plugin-shortcode-core/commit/16013bcb70f28b6aaeb227c30a5192f3d22ebf0c

**Comment by Erreur32** [comment]
Yes ! the fix is working well.
