### ISSUE TITLE
Possible update issue with latest release

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-shortcode-core#84]
I've noticed an error message on several projects when updating all plugins, and I was able to finally take a screenshot of it:

![2020-03-02_13-59-49](https://user-images.githubusercontent.com/1812771/75722119-7407c880-5c8e-11ea-91f2-9f49fc0fdc4d.png)

To replicate, download an earlier version of Grav with the ShortCode Plugin installed and then update Grav/all Plugins:
https://github.com/hibbitts-design/grav-skeleton-course-hub/releases/tag/v3.1.1

Please let me know if any more info is helpful.

Thanks very much,
Paul

**Comment by rhukster** [comment]
Could it be that your skeleton has that file missing?

**Comment by paulhibbitts** [comment]
That's a good point - I just also tested with Ole's Presentation Skeleton (with ShortCode installed, but needed to be updated) and get what looks to be the same error:

![2020-03-02_17-43-36](https://user-images.githubusercontent.com/1812771/75734693-7b8a9a00-5cad-11ea-8130-7a9a71002b2d.png)
https://github.com/OleVik/grav-skeleton-presentation/releases/tag/v1.0.2

I've seen the odd comment in the Discord room regarding updating the ShortCode Plugin recently but only now figured a way to capture the error message (it only flashes on the screen).

Thanks very much,
Paul

**Comment by mahagr** [comment]
Looks like opcode caching issue to me -- the class was moved into another folder. Also, the code has been updated so that there's no such require() in the method above.

This means that the error comes because of Grav is trying to load the old version of the PHP file and fails because of that.

**Comment by Erreur32** [comment]
And is there a fix/workaround  for that ?
