### ISSUE TITLE
shortcode in title causes html breakage

### ISSUE THREAD

**Issue by tg-x** [getgrav/grav-plugin-shortcode-core#89]
Using FA shortcodes in titles results in HTML breakage that was introduced recently, it used to work fine before but broke after an update to latest grav and latest shortcode plugins.

```
## [fa=play] Test
```

results in

```
<h2 id="fa-play-test" class="headeranchor">
  <a class="headeranchor-link headeranchor-link--left headeranchor-visible--hover" aria-hidden="true" href="#fa-play-test" title="Permanent link: <i class="fa fa-play"></i> Test" data-icon="#"><i class="fa fa-play"></i> Test</a>
</h2>
```

The `<a>` comes from the TOC plugin, which uses the unquoted HTML source of the rendered shortcode in the `title` attribute for some reason.

Upon further inspection, [TOC actually applies  `strip_tags`](https://github.com/Sommerregen/grav-plugin-toc/blob/develop/classes/Toc.php#L176) on the `title` attribute, but for some reason it does not strip it anymore, likely short code processing happens after other plugins get to process the content.

Also, shortcode source should not be added to the the `h2` `id `attribute, thus should be `<h2 id="test">` instead

**Comment by rhukster** [comment]
Looks like your other plugins are causing this.. just tested and got:

```
<h2><i class="fa fa-play"></i> Test FA shortcode in header</h2>
```

As expected.
