### ISSUE TITLE
Call to undefined method Grav\Common\Page\Page::getContentMeta()

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav-plugin-shortcode-core#9]
After updating to latest version shortcode-core (i guess) gives that error.
Location: /user/plugins/shortcode-core/shortcode-core.php

Highlighted line: 
```
// get the meta and check for assets
$meta = $page->getContentMeta();
```

**Comment by flaviocopes** [comment]
Upgrade to the latest Grav version, that method was added to the latest release

**Comment by lid3rs** [comment]
Thank you! For others: bin/gpm selfupgrade
