### ISSUE TITLE
Make the registering of shortcodes provided with this plugin optional

### ISSUE THREAD

**Issue by tintincastro** [getgrav/grav-plugin-shortcode-core#90]
Hello,

Firstly, thanks for such a useful plugin.

A nice configuration option for this plugin would be the possibility to disable the loading of default shortcodes (something such as `do_not_register_defaults_shortcodes: true` in the configuration yaml for example, set to false by default so it would'nt break compatibility).

Because some of the provided shortcode might not fit the philosophy of a website. As an example, you could develop a theme that do use something else than fontawesome as an icon set or you might want to add accessible attributes to their markup...

This way, people would be able to register only the shortcode they want to make available, by using the registerShortcode method in the ShortcodeHandlers event of their theme or plugin.

Have a nice day!

**Comment by tintincastro** [comment]
Well, seems PR #86 adresses this very question ;-) So I won't bother you anymore here.

**Comment by rhukster** [comment]
merged!

**Comment by tintincastro** [comment]
Thank you!
